project:
  type: website
  output-dir: docs

website:
  title: "website_bits"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: images.qmd
        text: Images
      - href: charts.qmd
        text: Charts
      - href: about.qmd
        text: About
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



